assets: LIBERO_PRO/libero/libero/assets
bddl_files: LIBERO_PRO/libero/libero/bddl_files
benchmark_root: LIBERO_PRO/libero/libero
datasets: LIBERO_PRO/libero/libero/datasets
init_states: LIBERO_PRO/libero/libero/init_files
